"""add_requires_document_to_leave_types

Revision ID: 17c7370bad5c
Revises: 3abfbb8bab38
Create Date: 2026-07-09 15:56:00.899342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c7370bad5c'
down_revision: Union[str, Sequence[str], None] = '3abfbb8bab38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_types', sa.Column('requires_document', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_types', 'requires_document')
    # ### end Alembic commands ###
