"""make_department_id_nullable

Revision ID: 21bf08bda85f
Revises: e2288df432be
Create Date: 2026-07-11 18:17:34.427496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21bf08bda85f'
down_revision: Union[str, Sequence[str], None] = 'e2288df432be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parent_projects', 'department_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('projects', 'department_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'department_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('parent_projects', 'department_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
