"""add_document_url_to_leave_requests

Revision ID: 3abfbb8bab38
Revises: e2aaedc7aae8
Create Date: 2026-07-09 15:49:02.017651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3abfbb8bab38'
down_revision: Union[str, Sequence[str], None] = 'e2aaedc7aae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('document_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_requests', 'document_url')
    # ### end Alembic commands ###
