"""add_missed_clockin_requests

Revision ID: 4e8c6383e48f
Revises: 17c7370bad5c
Create Date: 2026-07-09 17:07:40.321406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8c6383e48f'
down_revision: Union[str, Sequence[str], None] = '17c7370bad5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missed_clockin_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('requested_clock_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missed_clockin_requests_employee_id'), 'missed_clockin_requests', ['employee_id'], unique=False)
    op.create_index('ix_missed_clockin_requests_reviewed_by', 'missed_clockin_requests', ['reviewed_by'], unique=False)
    op.create_index('uq_missed_clockin_pending_per_day', 'missed_clockin_requests', ['employee_id', 'attendance_date'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_missed_clockin_pending_per_day', table_name='missed_clockin_requests', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_missed_clockin_requests_reviewed_by', table_name='missed_clockin_requests')
    op.drop_index(op.f('ix_missed_clockin_requests_employee_id'), table_name='missed_clockin_requests')
    op.drop_table('missed_clockin_requests')
    # ### end Alembic commands ###
