"""add_ticket_management_module

Revision ID: 6ec0430a9503
Revises: e025f13bf205
Create Date: 2026-07-13 16:44:32.251919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec0430a9503'
down_revision: Union[str, Sequence[str], None] = 'e025f13bf205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ticket_priorities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ticket_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ticket_category_handlers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ticket_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_ticket_category_employee', 'ticket_category_handlers', ['category_id', 'employee_id'], unique=True)
    op.create_table('ticket_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ticket_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_number', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('ticket_type_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('raised_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['ticket_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['priority_id'], ['ticket_priorities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raised_by_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['ticket_statuses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_ticket_number'), 'tickets', ['ticket_number'], unique=True)
    op.create_table('ticket_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('commented_by_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commented_by_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('performed_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- Seed Ticket Configurations & Features ---
    import uuid
    from sqlalchemy.orm import Session
    bind = op.get_bind()
    session = Session(bind=bind)

    # 1. Seed Ticket Categories
    categories = [
        {"id": uuid.UUID("11111111-1111-1111-1111-111111111111"), "name": "IT", "is_active": True},
        {"id": uuid.UUID("22222222-2222-2222-2222-222222222222"), "name": "Stationery", "is_active": True}
    ]
    for cat in categories:
        session.execute(
            sa.text("INSERT INTO ticket_categories (id, name, is_active, created_at, updated_at) "
                    "VALUES (:id, :name, :is_active, now(), now()) ON CONFLICT (name) DO NOTHING"),
            cat
        )

    # 2. Seed Ticket Priorities
    priorities = ["Low", "Medium", "High", "Critical"]
    for prio in priorities:
        session.execute(
            sa.text("INSERT INTO ticket_priorities (id, name, is_active, created_at, updated_at) "
                    "VALUES (:id, :name, true, now(), now()) ON CONFLICT (name) DO NOTHING"),
            {"id": uuid.uuid4(), "name": prio}
        )

    # 3. Seed Ticket Statuses
    statuses = ["Open", "In Progress", "On Hold", "Resolved", "Closed"]
    for stat in statuses:
        session.execute(
            sa.text("INSERT INTO ticket_statuses (id, name, is_active, created_at, updated_at) "
                    "VALUES (:id, :name, true, now(), now()) ON CONFLICT (name) DO NOTHING"),
            {"id": uuid.uuid4(), "name": stat}
        )

    # 4. Seed Module & Features for RBAC
    tickets_module_id = uuid.uuid4()
    session.execute(
        sa.text("INSERT INTO modules (id, module_key, module_name, display_order, icon, is_active, created_at) "
                "VALUES (:id, 'tickets', 'Tickets', 11, 'ConfirmationNumberOutlinedIcon', true, now()) "
                "ON CONFLICT (module_key) DO NOTHING"),
        {"id": tickets_module_id}
    )

    mod_row = session.execute(
        sa.text("SELECT id FROM modules WHERE module_key = 'tickets'")
    ).fetchone()
    if mod_row:
        tickets_module_id = mod_row[0]

    features_to_seed = [
        ("raise_ticket", "Raise Ticket", "/tickets/my/raise", 1, False),
        ("my_tickets", "My Tickets", "/tickets/my", 2, True),
        ("category_tickets", "Support Tickets", "/tickets/category", 3, True)
    ]
    for feat_key, feat_name, route, order, menu_vis in features_to_seed:
        session.execute(
            sa.text("INSERT INTO features (id, module_id, feature_key, feature_name, route, icon, display_order, "
                    "menu_visible, permission_enabled, is_system, is_active, created_at) "
                    "VALUES (:id, :module_id, :feature_key, :feature_name, :route, null, :display_order, "
                    ":menu_visible, true, false, true, now()) ON CONFLICT (feature_key) DO NOTHING"),
            {"id": uuid.uuid4(), "module_id": tickets_module_id, "feature_key": feat_key, "feature_name": feat_name,
             "route": route, "display_order": order, "menu_visible": menu_vis}
        )

    settings_mod = session.execute(
        sa.text("SELECT id FROM modules WHERE module_key = 'settings'")
    ).fetchone()
    if settings_mod:
        settings_module_id = settings_mod[0]
        session.execute(
            sa.text("INSERT INTO features (id, module_id, feature_key, feature_name, route, icon, display_order, "
                    "menu_visible, permission_enabled, is_system, is_active, created_at) "
                    "VALUES (:id, :module_id, 'ticket_settings', 'Ticket Settings', '/settings/tickets', null, 10, "
                    "false, true, false, true, now()) ON CONFLICT (feature_key) DO NOTHING"),
            {"id": uuid.uuid4(), "module_id": settings_module_id}
        )

    # 5. Grant Default Permissions to Roles
    roles = session.execute(sa.text("SELECT id, role_code FROM roles")).fetchall()
    
    feat_ids = {}
    for fk in ["raise_ticket", "my_tickets", "category_tickets", "ticket_settings"]:
        frow = session.execute(sa.text("SELECT id FROM features WHERE feature_key = :fk"), {"fk": fk}).fetchone()
        if frow:
            feat_ids[fk] = frow[0]

    for role_id, role_code in roles:
        for fk in ["raise_ticket", "my_tickets"]:
            if fk in feat_ids:
                existing = session.execute(
                    sa.text("SELECT id FROM role_permissions WHERE role_id = :role_id AND feature_id = :feature_id"),
                    {"role_id": role_id, "feature_id": feat_ids[fk]}
                ).fetchone()
                if not existing:
                    session.execute(
                        sa.text("INSERT INTO role_permissions (id, role_id, feature_id, module_name, view_scope, create_scope, update_scope, delete_scope) "
                                "VALUES (:id, :role_id, :feature_id, null, 'ALL', 'ALL', 'ALL', 'ALL')"),
                        {"id": uuid.uuid4(), "role_id": role_id, "feature_id": feat_ids[fk]}
                    )
        if role_code == "ADMIN":
            for fk in ["ticket_settings", "category_tickets"]:
                if fk in feat_ids:
                    existing = session.execute(
                        sa.text("SELECT id FROM role_permissions WHERE role_id = :role_id AND feature_id = :feature_id"),
                        {"role_id": role_id, "feature_id": feat_ids[fk]}
                    ).fetchone()
                    if not existing:
                        session.execute(
                            sa.text("INSERT INTO role_permissions (id, role_id, feature_id, module_name, view_scope, create_scope, update_scope, delete_scope) "
                                    "VALUES (:id, :role_id, :feature_id, null, 'ALL', 'ALL', 'ALL', 'ALL')"),
                            {"id": uuid.uuid4(), "role_id": role_id, "feature_id": feat_ids[fk]}
                        )
    session.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # Clean up seeded modules, features, and role permissions
    from sqlalchemy.orm import Session
    bind = op.get_bind()
    session = Session(bind=bind)
    
    session.execute(sa.text("DELETE FROM role_permissions WHERE feature_id IN (SELECT id FROM features WHERE feature_key IN ('raise_ticket', 'my_tickets', 'category_tickets', 'ticket_settings'))"))
    session.execute(sa.text("DELETE FROM features WHERE feature_key IN ('raise_ticket', 'my_tickets', 'category_tickets', 'ticket_settings')"))
    session.execute(sa.text("DELETE FROM modules WHERE module_key = 'tickets'"))
    session.commit()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_histories')
    op.drop_table('ticket_comments')
    op.drop_table('ticket_attachments')
    op.drop_index(op.f('ix_tickets_ticket_number'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('ticket_types')
    op.drop_index('uq_ticket_category_employee', table_name='ticket_category_handlers')
    op.drop_table('ticket_category_handlers')
    op.drop_table('ticket_statuses')
    op.drop_table('ticket_priorities')
    op.drop_table('ticket_categories')
    # ### end Alembic commands ###
