"""add_team_assignment_to_tasks

Revision ID: 8e637e252237
Revises: 0004_task_templates
Create Date: 2026-06-26 11:32:29.270746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e637e252237'
down_revision: Union[str, Sequence[str], None] = '0004_task_templates'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.create_index('ix_departments_department_head_id', 'departments', ['department_head_id'], unique=False)
    op.create_index('ix_departments_is_active', 'departments', ['is_active'], unique=False)
    op.create_unique_constraint(None, 'departments', ['name'])
    op.create_unique_constraint(None, 'departments', ['code'])
    op.alter_column('designations', 'department_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_designations_name'), table_name='designations')
    op.create_index('ix_designations_is_active', 'designations', ['is_active'], unique=False)
    op.drop_constraint(op.f('designations_department_id_fkey'), 'designations', type_='foreignkey')
    op.create_foreign_key(None, 'designations', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_employee_reporting_history_employee_id'), table_name='employee_reporting_history')
    op.create_index('ix_emp_reporting_history_employee_changed_at', 'employee_reporting_history', ['employee_id', 'changed_at'], unique=False)
    op.create_index('ix_emp_reporting_history_employee_id', 'employee_reporting_history', ['employee_id'], unique=False)
    op.create_index('ix_emp_reporting_history_new_manager_id', 'employee_reporting_history', ['new_manager_id'], unique=False)
    op.create_index('ix_emp_reporting_history_old_manager_id', 'employee_reporting_history', ['old_manager_id'], unique=False)
    op.alter_column('employee_role_history', 'new_role_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_employee_role_history_employee_id'), table_name='employee_role_history')
    op.create_index('ix_erh_effective_dates', 'employee_role_history', ['employee_id', 'effective_from', 'effective_to'], unique=False)
    op.create_index('ix_erh_employee_id', 'employee_role_history', ['employee_id'], unique=False)
    op.drop_constraint(op.f('employee_role_history_new_role_id_fkey'), 'employee_role_history', type_='foreignkey')
    op.create_foreign_key(None, 'employee_role_history', 'roles', ['new_role_id'], ['id'], ondelete='SET NULL')
    op.alter_column('employees', 'gender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_official_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.create_index('ix_employees_account_status', 'employees', ['account_status'], unique=False)
    op.create_index('ix_employees_is_active', 'employees', ['is_active'], unique=False)
    op.create_unique_constraint(None, 'employees', ['email'])
    op.create_unique_constraint(None, 'employees', ['username'])
    op.create_unique_constraint(None, 'employees', ['employee_code'])
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=False)
    op.add_column('projects', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_index('ix_projects_department_id', 'projects', ['department_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'departments', ['department_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('roles', 'data_access_level',
               existing_type=sa.VARCHAR(length=20),
               comment='Row-level data visibility: FULL, MANAGED, TEAM, SELF',
               existing_nullable=False,
               existing_server_default=sa.text("'SELF'::character varying"))
    op.create_index('ix_roles_is_active', 'roles', ['is_active'], unique=False)
    op.drop_index(op.f('ix_task_templates_is_active'), table_name='task_templates')
    op.drop_index(op.f('ix_task_templates_title'), table_name='task_templates')
    op.add_column('tasks', sa.Column('team_id', sa.UUID(), nullable=True))
    op.create_index('ix_tasks_team_id', 'tasks', ['team_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'teams', ['team_id'], ['id'], ondelete='RESTRICT')

    # --- Backfill Logic for Existing Data ---
    connection = op.get_bind()
    dept = connection.execute(sa.text("SELECT id FROM departments LIMIT 1")).fetchone()
    if dept:
        default_dept_id = dept[0]
    else:
        import uuid
        default_dept_id = uuid.uuid4()
        connection.execute(
            sa.text("INSERT INTO departments (id, name, code, is_active, created_at, updated_at) VALUES (:id, 'General', 'GEN', true, now(), now())"),
            {"id": default_dept_id}
        )

    # Update existing projects to the default department
    connection.execute(
        sa.text("UPDATE projects SET department_id = :dept_id WHERE department_id IS NULL"),
        {"dept_id": default_dept_id}
    )

    # Find a default team belonging to that department
    team = connection.execute(
        sa.text("SELECT id FROM teams WHERE department_id = :dept_id LIMIT 1"),
        {"dept_id": default_dept_id}
    ).fetchone()
    
    if team:
        default_team_id = team[0]
    else:
        import uuid
        default_team_id = uuid.uuid4()
        connection.execute(
            sa.text("INSERT INTO teams (id, team_name, team_code, department_id, is_active, created_at, updated_at) VALUES (:id, 'General Team', 'GEN_TEAM', :dept_id, true, now(), now())"),
            {"id": default_team_id, "dept_id": default_dept_id}
        )

    # Update existing tasks to the default team
    connection.execute(
        sa.text("UPDATE tasks SET team_id = :team_id WHERE team_id IS NULL"),
        {"team_id": default_team_id}
    )

    # Alter columns to NOT NULL now that everything is backfilled
    op.alter_column('projects', 'department_id', nullable=False)
    op.alter_column('tasks', 'team_id', nullable=False)

    op.drop_index(op.f('uq_team_members_primary_team'), table_name='team_members', postgresql_where='(is_primary_team = true)')
    op.drop_index(op.f('ix_teams_team_code'), table_name='teams')
    op.drop_index(op.f('ix_teams_team_name'), table_name='teams')
    op.create_index('ix_teams_is_active', 'teams', ['is_active'], unique=False)
    op.create_unique_constraint(None, 'teams', ['team_code'])
    op.create_unique_constraint(None, 'teams', ['team_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_index('ix_teams_is_active', table_name='teams')
    op.create_index(op.f('ix_teams_team_name'), 'teams', ['team_name'], unique=True)
    op.create_index(op.f('ix_teams_team_code'), 'teams', ['team_code'], unique=True)
    op.create_index(op.f('uq_team_members_primary_team'), 'team_members', ['employee_id'], unique=True, postgresql_where='(is_primary_team = true)')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index('ix_tasks_team_id', table_name='tasks')
    op.drop_column('tasks', 'team_id')
    op.create_index(op.f('ix_task_templates_title'), 'task_templates', ['title'], unique=False)
    op.create_index(op.f('ix_task_templates_is_active'), 'task_templates', ['is_active'], unique=False)
    op.drop_index('ix_roles_is_active', table_name='roles')
    op.alter_column('roles', 'data_access_level',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Row-level data visibility: FULL, MANAGED, TEAM, SELF',
               existing_nullable=False,
               existing_server_default=sa.text("'SELF'::character varying"))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index('ix_projects_department_id', table_name='projects')
    op.drop_column('projects', 'department_id')
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=True)
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_index('ix_employees_is_active', table_name='employees')
    op.drop_index('ix_employees_account_status', table_name='employees')
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    op.create_index(op.f('ix_employees_official_email'), 'employees', ['official_email'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.alter_column('employees', 'gender',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_constraint(None, 'employee_role_history', type_='foreignkey')
    op.create_foreign_key(op.f('employee_role_history_new_role_id_fkey'), 'employee_role_history', 'roles', ['new_role_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_erh_employee_id', table_name='employee_role_history')
    op.drop_index('ix_erh_effective_dates', table_name='employee_role_history')
    op.create_index(op.f('ix_employee_role_history_employee_id'), 'employee_role_history', ['employee_id'], unique=False)
    op.alter_column('employee_role_history', 'new_role_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_emp_reporting_history_old_manager_id', table_name='employee_reporting_history')
    op.drop_index('ix_emp_reporting_history_new_manager_id', table_name='employee_reporting_history')
    op.drop_index('ix_emp_reporting_history_employee_id', table_name='employee_reporting_history')
    op.drop_index('ix_emp_reporting_history_employee_changed_at', table_name='employee_reporting_history')
    op.create_index(op.f('ix_employee_reporting_history_employee_id'), 'employee_reporting_history', ['employee_id'], unique=False)
    op.drop_constraint(None, 'designations', type_='foreignkey')
    op.create_foreign_key(op.f('designations_department_id_fkey'), 'designations', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_designations_is_active', table_name='designations')
    op.create_index(op.f('ix_designations_name'), 'designations', ['name'], unique=False)
    op.alter_column('designations', 'department_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'departments', type_='unique')
    op.drop_constraint(None, 'departments', type_='unique')
    op.drop_index('ix_departments_is_active', table_name='departments')
    op.drop_index('ix_departments_department_head_id', table_name='departments')
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    # ### end Alembic commands ###
