"""make_bm_normalized_log_employee_id_nullable

Revision ID: b382bc5a8dd3
Revises: 8fca154a9b6d
Create Date: 2026-08-03 17:20:39.527538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b382bc5a8dd3'
down_revision: Union[str, Sequence[str], None] = '8fca154a9b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_marked_by'), table_name='attendance')
    op.alter_column('bm_normalized_logs', 'employee_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_bm_norm_logs_emp_time'), table_name='bm_normalized_logs')
    op.create_foreign_key(None, 'departments', 'employees', ['department_head_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('uq_employee_breaks_one_open_per_employee'), table_name='employee_breaks', postgresql_where='(break_end IS NULL)')
    op.create_unique_constraint('uq_project_member', 'project_members', ['project_id', 'employee_id'])
    op.create_index('ix_revoked_tokens_expires_at', 'revoked_tokens', ['expires_at'], unique=False)
    op.create_unique_constraint('uq_role_feature', 'role_permissions', ['role_id', 'feature_id'])
    op.drop_index(op.f('ix_task_work_sessions_ended_by'), table_name='task_work_sessions')
    op.drop_index(op.f('ix_task_work_sessions_started_by'), table_name='task_work_sessions')
    op.drop_index(op.f('uq_task_work_sessions_one_running_per_employee'), table_name='task_work_sessions', postgresql_where="((status)::text = 'RUNNING'::text)")
    op.add_column('ticket_category_handlers', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.drop_index(op.f('ix_time_entries_approved_by'), table_name='time_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_time_entries_approved_by'), 'time_entries', ['approved_by'], unique=False)
    op.drop_column('ticket_category_handlers', 'is_active')
    op.create_index(op.f('uq_task_work_sessions_one_running_per_employee'), 'task_work_sessions', ['employee_id'], unique=True, postgresql_where="((status)::text = 'RUNNING'::text)")
    op.create_index(op.f('ix_task_work_sessions_started_by'), 'task_work_sessions', ['started_by'], unique=False)
    op.create_index(op.f('ix_task_work_sessions_ended_by'), 'task_work_sessions', ['ended_by'], unique=False)
    op.drop_constraint('uq_role_feature', 'role_permissions', type_='unique')
    op.drop_index('ix_revoked_tokens_expires_at', table_name='revoked_tokens')
    op.drop_constraint('uq_project_member', 'project_members', type_='unique')
    op.create_index(op.f('uq_employee_breaks_one_open_per_employee'), 'employee_breaks', ['employee_id'], unique=True, postgresql_where='(break_end IS NULL)')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_index(op.f('ix_bm_norm_logs_emp_time'), 'bm_normalized_logs', ['employee_id', 'punch_timestamp'], unique=False)
    op.alter_column('bm_normalized_logs', 'employee_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_attendance_marked_by'), 'attendance', ['marked_by'], unique=False)
    # ### end Alembic commands ###
