"""add_task_continuity_tables

Revision ID: cb9c86269157
Revises: f6a8833e5481
Create Date: 2026-06-28 15:06:57.440586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9c86269157'
down_revision: Union[str, Sequence[str], None] = 'f6a8833e5481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_delegations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('delegate_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('delegated_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delegate_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delegated_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_delegations_delegate_id', 'task_delegations', ['delegate_id'], unique=False)
    op.create_index('ix_task_delegations_owner_id', 'task_delegations', ['owner_id'], unique=False)
    op.create_index('ix_task_delegations_task_id', 'task_delegations', ['task_id'], unique=False)
    op.create_table('task_pause_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paused_by', sa.UUID(), nullable=True),
    sa.Column('resumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resumed_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['paused_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resumed_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_pause_history_task_id', 'task_pause_history', ['task_id'], unique=False)
    op.create_table('task_transfer_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('from_employee_id', sa.UUID(), nullable=True),
    sa.Column('to_employee_id', sa.UUID(), nullable=True),
    sa.Column('transfer_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('remaining_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('transfer_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['from_employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_transfer_history_task_id', 'task_transfer_history', ['task_id'], unique=False)
    op.create_table('task_risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_request_id', sa.UUID(), nullable=False),
    sa.Column('leave_start_date', sa.Date(), nullable=False),
    sa.Column('leave_end_date', sa.Date(), nullable=False),
    sa.Column('remaining_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('days_impacted', sa.Integer(), nullable=False),
    sa.Column('project_impact', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['task_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_request_id'], ['leave_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_risks_employee_id', 'task_risks', ['employee_id'], unique=False)
    op.create_index('ix_task_risks_status', 'task_risks', ['status'], unique=False)
    op.create_index('ix_task_risks_task_id', 'task_risks', ['task_id'], unique=False)
    op.create_table('manager_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_risk_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_risk_id'], ['task_risks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_manager_decisions_task_id', 'manager_decisions', ['task_id'], unique=False)
    op.create_index('ix_manager_decisions_task_risk_id', 'manager_decisions', ['task_risk_id'], unique=False)
    op.create_foreign_key(None, 'departments', 'employees', ['department_head_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_index('ix_manager_decisions_task_risk_id', table_name='manager_decisions')
    op.drop_index('ix_manager_decisions_task_id', table_name='manager_decisions')
    op.drop_table('manager_decisions')
    op.drop_index('ix_task_risks_task_id', table_name='task_risks')
    op.drop_index('ix_task_risks_status', table_name='task_risks')
    op.drop_index('ix_task_risks_employee_id', table_name='task_risks')
    op.drop_table('task_risks')
    op.drop_index('ix_task_transfer_history_task_id', table_name='task_transfer_history')
    op.drop_table('task_transfer_history')
    op.drop_index('ix_task_pause_history_task_id', table_name='task_pause_history')
    op.drop_table('task_pause_history')
    op.drop_index('ix_task_delegations_task_id', table_name='task_delegations')
    op.drop_index('ix_task_delegations_owner_id', table_name='task_delegations')
    op.drop_index('ix_task_delegations_delegate_id', table_name='task_delegations')
    op.drop_table('task_delegations')
    # ### end Alembic commands ###
