"""add_half_day_to_leave_requests

Revision ID: e2288df432be
Revises: 4e8c6383e48f
Create Date: 2026-07-11 15:14:26.864440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2288df432be'
down_revision: Union[str, Sequence[str], None] = '4e8c6383e48f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_requests', sa.Column('is_half_day', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('leave_requests', sa.Column('half_day_session', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_requests', 'half_day_session')
    op.drop_column('leave_requests', 'is_half_day')
    # ### end Alembic commands ###
