"""add_approval_engine

Revision ID: e2aaedc7aae8
Revises: 71b41c4a8ddb
Create Date: 2026-07-09 13:42:21.983468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2aaedc7aae8'
down_revision: Union[str, Sequence[str], None] = '71b41c4a8ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('module_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approval_strategy', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_workflows_is_active', 'approval_workflows', ['is_active'], unique=False)
    op.create_index('ix_approval_workflows_module_type', 'approval_workflows', ['module_type'], unique=False)
    op.create_table('approval_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('workflow_version', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('approver_role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_approver_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('actioned_by_id', sa.UUID(), nullable=True),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('resolved_by_scope', sa.String(length=50), nullable=True),
    sa.Column('resolved_approver_id', sa.UUID(), nullable=True),
    sa.Column('resolution_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actioned_by_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['approver_role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_approver_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_approver_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_instances_assigned_approver_id', 'approval_instances', ['assigned_approver_id'], unique=False)
    op.create_index('ix_approval_instances_module_target', 'approval_instances', ['module_type', 'target_id'], unique=False)
    op.create_index('ix_approval_instances_status', 'approval_instances', ['status'], unique=False)
    op.create_table('approval_workflow_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('requester_role_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('approver_role_id', sa.UUID(), nullable=False),
    sa.Column('resolution_scope', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['approver_role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_workflow_steps_requester_role_id', 'approval_workflow_steps', ['requester_role_id'], unique=False)
    op.create_index('ix_approval_workflow_steps_workflow_id', 'approval_workflow_steps', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_approval_workflow_steps_workflow_id', table_name='approval_workflow_steps')
    op.drop_index('ix_approval_workflow_steps_requester_role_id', table_name='approval_workflow_steps')
    op.drop_table('approval_workflow_steps')
    op.drop_index('ix_approval_instances_status', table_name='approval_instances')
    op.drop_index('ix_approval_instances_module_target', table_name='approval_instances')
    op.drop_index('ix_approval_instances_assigned_approver_id', table_name='approval_instances')
    op.drop_table('approval_instances')
    op.drop_index('ix_approval_workflows_module_type', table_name='approval_workflows')
    op.drop_index('ix_approval_workflows_is_active', table_name='approval_workflows')
    op.drop_table('approval_workflows')
    # ### end Alembic commands ###
