"""initial_migration

Revision ID: f3bfb2e8f71e
Revises: 
Create Date: 2026-06-23 22:26:15.026506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3bfb2e8f71e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('office_start_time', sa.String(length=5), nullable=False),
    sa.Column('office_end_time', sa.String(length=5), nullable=False),
    sa.Column('half_day_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('late_mark_after_minutes', sa.Integer(), nullable=False),
    sa.Column('work_days', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_head_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_departments_department_head_id', 'departments', ['department_head_id'], unique=False)
    op.create_index('ix_departments_is_active', 'departments', ['is_active'], unique=False)
    op.create_table('designations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_designations_department_id', 'designations', ['department_id'], unique=False)
    op.create_index('ix_designations_is_active', 'designations', ['is_active'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('official_email', sa.String(length=255), nullable=True),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=True),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('profile_photo_url', sa.Text(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('designation_id', sa.UUID(), nullable=True),
    sa.Column('reporting_manager_id', sa.UUID(), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.String(length=20), nullable=True),
    sa.Column('account_status', sa.String(length=20), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_code'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_employees_account_status', 'employees', ['account_status'], unique=False)
    op.create_index('ix_employees_department_id', 'employees', ['department_id'], unique=False)
    op.create_index('ix_employees_designation_id', 'employees', ['designation_id'], unique=False)
    op.create_index('ix_employees_is_active', 'employees', ['is_active'], unique=False)
    op.create_index('ix_employees_reporting_manager_id', 'employees', ['reporting_manager_id'], unique=False)
    op.create_table('holidays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=True)
    op.create_table('leave_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('days_per_year', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_carry_forward', sa.Boolean(), nullable=False),
    sa.Column('max_carry_forward_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('revoked_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_role_id', sa.UUID(), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('data_access_level', sa.String(length=20), server_default='SELF', nullable=False, comment='Row-level data visibility: FULL, MANAGED, TEAM, SELF'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roles_is_active', 'roles', ['is_active'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_parent_role_id'), 'roles', ['parent_role_id'], unique=False)
    op.create_index(op.f('ix_roles_role_code'), 'roles', ['role_code'], unique=True)
    op.create_table('scope_of_work',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('department_category', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_of_work_code'), 'scope_of_work', ['code'], unique=True)
    op.create_index('ix_scope_of_work_department_category', 'scope_of_work', ['department_category'], unique=False)
    op.create_index('ix_scope_of_work_is_active', 'scope_of_work', ['is_active'], unique=False)
    op.create_index(op.f('ix_scope_of_work_name'), 'scope_of_work', ['name'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('clock_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clock_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('late_by_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('marked_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_attendance_per_day')
    )
    op.create_index('ix_attendance_date', 'attendance', ['date'], unique=False)
    op.create_index('ix_attendance_employee_id', 'attendance', ['employee_id'], unique=False)
    op.create_index('ix_attendance_status', 'attendance', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_performed_at', 'audit_logs', ['performed_at'], unique=False)
    op.create_index('ix_audit_logs_performed_by', 'audit_logs', ['performed_by'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('alternate_phone', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='Active', nullable=False),
    sa.Column('deactivation_reason', sa.Text(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_by', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_client_code'), 'clients', ['client_code'], unique=True)
    op.create_index('ix_clients_created_by', 'clients', ['created_by'], unique=False)
    op.create_index('ix_clients_is_active', 'clients', ['is_active'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.create_table('employee_breaks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('break_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('break_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emp_breaks_date', 'employee_breaks', ['date'], unique=False)
    op.create_index('ix_emp_breaks_employee_id', 'employee_breaks', ['employee_id'], unique=False)
    op.create_table('employee_reporting_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('old_manager_id', sa.UUID(), nullable=True),
    sa.Column('new_manager_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emp_reporting_history_employee_changed_at', 'employee_reporting_history', ['employee_id', 'changed_at'], unique=False)
    op.create_index('ix_emp_reporting_history_employee_id', 'employee_reporting_history', ['employee_id'], unique=False)
    op.create_index('ix_emp_reporting_history_new_manager_id', 'employee_reporting_history', ['new_manager_id'], unique=False)
    op.create_index('ix_emp_reporting_history_old_manager_id', 'employee_reporting_history', ['old_manager_id'], unique=False)
    op.create_table('employee_role_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('old_role_id', sa.UUID(), nullable=True),
    sa.Column('new_role_id', sa.UUID(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['old_role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_erh_effective_dates', 'employee_role_history', ['employee_id', 'effective_from', 'effective_to'], unique=False)
    op.create_index('ix_erh_employee_id', 'employee_role_history', ['employee_id'], unique=False)
    op.create_table('employee_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'role_id', name='uq_employee_role')
    )
    op.create_index('ix_employee_roles_employee_id', 'employee_roles', ['employee_id'], unique=False)
    op.create_index('ix_employee_roles_role_id', 'employee_roles', ['role_id'], unique=False)
    op.create_table('employee_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('available_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'week_start_date', name='uq_employee_week')
    )
    op.create_index('ix_employee_schedules_employee_id', 'employee_schedules', ['employee_id'], unique=False)
    op.create_table('leave_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_allowed', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('used', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('carried_forward', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'year', name='uq_leave_balance')
    )
    op.create_index('ix_leave_balances_employee_year', 'leave_balances', ['employee_id', 'year'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('hr_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leave_requests_employee_id', 'leave_requests', ['employee_id'], unique=False)
    op.create_index('ix_leave_requests_from_date', 'leave_requests', ['from_date'], unique=False)
    op.create_index('ix_leave_requests_leave_type_id', 'leave_requests', ['leave_type_id'], unique=False)
    op.create_index('ix_leave_requests_status', 'leave_requests', ['status'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('can_approve', sa.Boolean(), nullable=False),
    sa.Column('can_export', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'module_name', name='uq_role_module')
    )
    op.create_index(op.f('ix_role_permissions_module_name'), 'role_permissions', ['module_name'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_name', sa.String(length=200), nullable=False),
    sa.Column('team_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_code'),
    sa.UniqueConstraint('team_name')
    )
    op.create_index('ix_teams_department_id', 'teams', ['department_id'], unique=False)
    op.create_index('ix_teams_is_active', 'teams', ['is_active'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('part_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('project_manager_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('is_billable', sa.Boolean(), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('progress', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('contract_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('invoice_status', sa.String(length=30), nullable=False),
    sa.Column('tok_form', sa.String(length=100), nullable=True),
    sa.Column('feedback_status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_client_id', 'projects', ['client_id'], unique=False)
    op.create_index('ix_projects_created_by', 'projects', ['created_by'], unique=False)
    op.create_index('ix_projects_is_active', 'projects', ['is_active'], unique=False)
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_index('ix_projects_project_manager_id', 'projects', ['project_manager_id'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('role_in_team', sa.String(length=50), nullable=False),
    sa.Column('is_primary_team', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'employee_id', name='uq_team_member')
    )
    op.create_index('ix_team_members_employee_id', 'team_members', ['employee_id'], unique=False)
    op.create_index('ix_team_members_team_id', 'team_members', ['team_id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('allocation_pct', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_members_employee_id', 'project_members', ['employee_id'], unique=False)
    op.create_index('ix_project_members_project_id', 'project_members', ['project_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_code', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope_of_work_id', sa.UUID(), nullable=True),
    sa.Column('department_category', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('estimated_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('scheduled_start_date', sa.Date(), nullable=True),
    sa.Column('scheduled_end_date', sa.Date(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('planned_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('progress', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rework_count', sa.Integer(), nullable=False),
    sa.Column('total_rework_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('original_estimated_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_of_work_id'], ['scope_of_work.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'task_code', name='uq_task_code_per_project')
    )
    op.create_index('ix_tasks_department_category', 'tasks', ['department_category'], unique=False)
    op.create_index('ix_tasks_is_active', 'tasks', ['is_active'], unique=False)
    op.create_index('ix_tasks_parent_task_id', 'tasks', ['parent_task_id'], unique=False)
    op.create_index('ix_tasks_project_id', 'tasks', ['project_id'], unique=False)
    op.create_index('ix_tasks_scope_of_work_id', 'tasks', ['scope_of_work_id'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('task_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_assignments_employee_id', 'task_assignments', ['employee_id'], unique=False)
    op.create_index('ix_task_assignments_status', 'task_assignments', ['status'], unique=False)
    op.create_index('ix_task_assignments_task_id', 'task_assignments', ['task_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_task_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name='uq_task_dependency')
    )
    op.create_index('ix_task_dependencies_depends_on_task_id', 'task_dependencies', ['depends_on_task_id'], unique=False)
    op.create_index('ix_task_dependencies_task_id', 'task_dependencies', ['task_id'], unique=False)
    op.create_table('task_rework_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('rework_number', sa.Integer(), nullable=False),
    sa.Column('opened_by', sa.UUID(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('hours_spent', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opened_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trh_task_id', 'task_rework_history', ['task_id'], unique=False)
    op.create_table('task_work_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_by', sa.UUID(), nullable=True),
    sa.Column('ended_by', sa.UUID(), nullable=True),
    sa.Column('pause_reason', sa.String(length=500), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ended_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tws_employee_id', 'task_work_sessions', ['employee_id'], unique=False)
    op.create_index('ix_tws_employee_status', 'task_work_sessions', ['employee_id', 'status'], unique=False)
    op.create_index('ix_tws_project_id', 'task_work_sessions', ['project_id'], unique=False)
    op.create_index('ix_tws_status', 'task_work_sessions', ['status'], unique=False)
    op.create_index('ix_tws_task_id', 'task_work_sessions', ['task_id'], unique=False)
    op.create_table('time_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hours_spent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.Column('is_billable', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hours_spent > 0 AND hours_spent <= 24', name='ck_time_entries_hours_range'),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_time_entries_date', 'time_entries', ['date'], unique=False)
    op.create_index('ix_time_entries_employee_id', 'time_entries', ['employee_id'], unique=False)
    op.create_index('ix_time_entries_project_id', 'time_entries', ['project_id'], unique=False)
    op.create_index('ix_time_entries_status', 'time_entries', ['status'], unique=False)
    op.create_index('ix_time_entries_task_id', 'time_entries', ['task_id'], unique=False)
    op.create_foreign_key('fk_departments_department_head_id', 'departments', 'employees', ['department_head_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_time_entries_task_id', table_name='time_entries')
    op.drop_index('ix_time_entries_status', table_name='time_entries')
    op.drop_index('ix_time_entries_project_id', table_name='time_entries')
    op.drop_index('ix_time_entries_employee_id', table_name='time_entries')
    op.drop_index('ix_time_entries_date', table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index('ix_tws_task_id', table_name='task_work_sessions')
    op.drop_index('ix_tws_status', table_name='task_work_sessions')
    op.drop_index('ix_tws_project_id', table_name='task_work_sessions')
    op.drop_index('ix_tws_employee_status', table_name='task_work_sessions')
    op.drop_index('ix_tws_employee_id', table_name='task_work_sessions')
    op.drop_table('task_work_sessions')
    op.drop_index('ix_trh_task_id', table_name='task_rework_history')
    op.drop_table('task_rework_history')
    op.drop_index('ix_task_dependencies_task_id', table_name='task_dependencies')
    op.drop_index('ix_task_dependencies_depends_on_task_id', table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index('ix_task_assignments_task_id', table_name='task_assignments')
    op.drop_index('ix_task_assignments_status', table_name='task_assignments')
    op.drop_index('ix_task_assignments_employee_id', table_name='task_assignments')
    op.drop_table('task_assignments')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_scope_of_work_id', table_name='tasks')
    op.drop_index('ix_tasks_project_id', table_name='tasks')
    op.drop_index('ix_tasks_parent_task_id', table_name='tasks')
    op.drop_index('ix_tasks_is_active', table_name='tasks')
    op.drop_index('ix_tasks_department_category', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_project_members_project_id', table_name='project_members')
    op.drop_index('ix_project_members_employee_id', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index('ix_team_members_team_id', table_name='team_members')
    op.drop_index('ix_team_members_employee_id', table_name='team_members')
    op.drop_table('team_members')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_project_manager_id', table_name='projects')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_index('ix_projects_is_active', table_name='projects')
    op.drop_index('ix_projects_created_by', table_name='projects')
    op.drop_index('ix_projects_client_id', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_teams_is_active', table_name='teams')
    op.drop_index('ix_teams_department_id', table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_module_name'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_leave_requests_status', table_name='leave_requests')
    op.drop_index('ix_leave_requests_leave_type_id', table_name='leave_requests')
    op.drop_index('ix_leave_requests_from_date', table_name='leave_requests')
    op.drop_index('ix_leave_requests_employee_id', table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index('ix_leave_balances_employee_year', table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index('ix_employee_schedules_employee_id', table_name='employee_schedules')
    op.drop_table('employee_schedules')
    op.drop_index('ix_employee_roles_role_id', table_name='employee_roles')
    op.drop_index('ix_employee_roles_employee_id', table_name='employee_roles')
    op.drop_table('employee_roles')
    op.drop_index('ix_erh_employee_id', table_name='employee_role_history')
    op.drop_index('ix_erh_effective_dates', table_name='employee_role_history')
    op.drop_table('employee_role_history')
    op.drop_index('ix_emp_reporting_history_old_manager_id', table_name='employee_reporting_history')
    op.drop_index('ix_emp_reporting_history_new_manager_id', table_name='employee_reporting_history')
    op.drop_index('ix_emp_reporting_history_employee_id', table_name='employee_reporting_history')
    op.drop_index('ix_emp_reporting_history_employee_changed_at', table_name='employee_reporting_history')
    op.drop_table('employee_reporting_history')
    op.drop_index('ix_emp_breaks_employee_id', table_name='employee_breaks')
    op.drop_index('ix_emp_breaks_date', table_name='employee_breaks')
    op.drop_table('employee_breaks')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index('ix_clients_is_active', table_name='clients')
    op.drop_index('ix_clients_created_by', table_name='clients')
    op.drop_index(op.f('ix_clients_client_code'), table_name='clients')
    op.drop_table('clients')
    op.drop_index('ix_audit_logs_performed_by', table_name='audit_logs')
    op.drop_index('ix_audit_logs_performed_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_attendance_status', table_name='attendance')
    op.drop_index('ix_attendance_employee_id', table_name='attendance')
    op.drop_index('ix_attendance_date', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_scope_of_work_name'), table_name='scope_of_work')
    op.drop_index('ix_scope_of_work_is_active', table_name='scope_of_work')
    op.drop_index('ix_scope_of_work_department_category', table_name='scope_of_work')
    op.drop_index(op.f('ix_scope_of_work_code'), table_name='scope_of_work')
    op.drop_table('scope_of_work')
    op.drop_index(op.f('ix_roles_role_code'), table_name='roles')
    op.drop_index(op.f('ix_roles_parent_role_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index('ix_roles_is_active', table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_table('leave_types')
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index('ix_employees_reporting_manager_id', table_name='employees')
    op.drop_index('ix_employees_is_active', table_name='employees')
    op.drop_index('ix_employees_designation_id', table_name='employees')
    op.drop_index('ix_employees_department_id', table_name='employees')
    op.drop_index('ix_employees_account_status', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_designations_is_active', table_name='designations')
    op.drop_index('ix_designations_department_id', table_name='designations')
    op.drop_table('designations')
    op.drop_index('ix_departments_is_active', table_name='departments')
    op.drop_index('ix_departments_department_head_id', table_name='departments')
    op.drop_table('departments')
    op.drop_table('attendance_rules')
    # ### end Alembic commands ###
