"""extend_calendar_models

Revision ID: f6a8833e5481
Revises: 9a11b64dfce5
Create Date: 2026-06-26 22:26:33.656069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a8833e5481'
down_revision: Union[str, Sequence[str], None] = '9a11b64dfce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('affects_working_days', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('calendar_settings', sa.Column('enable_birthdays', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('calendar_settings', sa.Column('enable_company_events', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('calendar_settings', sa.Column('enable_holidays', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('calendar_settings', sa.Column('enable_task_events', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('calendar_settings', sa.Column('enable_project_events', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('calendar_settings', sa.Column('color_holiday', sa.String(length=7), server_default='#EF4444', nullable=False))
    op.add_column('calendar_settings', sa.Column('color_birthday', sa.String(length=7), server_default='#EC4899', nullable=False))
    op.add_column('calendar_settings', sa.Column('color_task', sa.String(length=7), server_default='#3B82F6', nullable=False))
    op.add_column('calendar_settings', sa.Column('color_project', sa.String(length=7), server_default='#10B981', nullable=False))
    op.add_column('calendar_settings', sa.Column('color_company_event', sa.String(length=7), server_default='#8B5CF6', nullable=False))
    op.add_column('holidays', sa.Column('affects_working_days', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holidays', 'affects_working_days')
    op.drop_column('calendar_settings', 'color_company_event')
    op.drop_column('calendar_settings', 'color_project')
    op.drop_column('calendar_settings', 'color_task')
    op.drop_column('calendar_settings', 'color_birthday')
    op.drop_column('calendar_settings', 'color_holiday')
    op.drop_column('calendar_settings', 'enable_project_events')
    op.drop_column('calendar_settings', 'enable_task_events')
    op.drop_column('calendar_settings', 'enable_holidays')
    op.drop_column('calendar_settings', 'enable_company_events')
    op.drop_column('calendar_settings', 'enable_birthdays')
    op.drop_column('calendar_events', 'affects_working_days')
    # ### end Alembic commands ###
