"""add_productivity_rules_and_idle_master

Revision ID: fc4997eeec63
Revises: 8e637e252237
Create Date: 2026-06-26 18:06:01.764315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4997eeec63'
down_revision: Union[str, Sequence[str], None] = '8e637e252237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idle_reason_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idle_reason_master_code'), 'idle_reason_master', ['code'], unique=True)
    op.create_table('idle_classifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('idle_segment_identifier', sa.String(length=100), nullable=False),
    sa.Column('reason_id', sa.UUID(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reason_id'], ['idle_reason_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', 'idle_segment_identifier', name='uq_idle_classifications')
    )
    op.create_index('ix_idle_class_emp_date', 'idle_classifications', ['employee_id', 'date'], unique=False)
    op.create_index(op.f('ix_idle_classifications_date'), 'idle_classifications', ['date'], unique=False)
    op.create_index(op.f('ix_idle_classifications_idle_segment_identifier'), 'idle_classifications', ['idle_segment_identifier'], unique=False)
    op.add_column('attendance_rules', sa.Column('required_productive_hours', sa.Numeric(precision=4, scale=2), server_default='8.0', nullable=False))
    op.add_column('attendance_rules', sa.Column('overtime_threshold_hours', sa.Numeric(precision=4, scale=2), server_default='9.0', nullable=False))
    op.add_column('attendance_rules', sa.Column('max_break_minutes', sa.Integer(), server_default='60', nullable=False))
    op.add_column('attendance_rules', sa.Column('min_break_minutes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_rules', 'min_break_minutes')
    op.drop_column('attendance_rules', 'max_break_minutes')
    op.drop_column('attendance_rules', 'overtime_threshold_hours')
    op.drop_column('attendance_rules', 'required_productive_hours')
    op.drop_index(op.f('ix_idle_classifications_idle_segment_identifier'), table_name='idle_classifications')
    op.drop_index(op.f('ix_idle_classifications_date'), table_name='idle_classifications')
    op.drop_index('ix_idle_class_emp_date', table_name='idle_classifications')
    op.drop_table('idle_classifications')
    op.drop_index(op.f('ix_idle_reason_master_code'), table_name='idle_reason_master')
    op.drop_table('idle_reason_master')
    # ### end Alembic commands ###
